language: node_js 
node_js:
  - "node"
python:
  - "3.6"
#This script should fix the "Error - Mocha permissions denied"
before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - npm install sequelize-cli
  - psql -c 'create database database_test;' -U postgres
  - sequelize db:migrate
  - sequelize db:seed:all
  - npm start &
  - sleep 3
  - python test/bin/station-sim.py3 -C test/cert/combined.pem -c localhost:3001 --no-verify -A user-access
